# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: michaelroubeiz-ca CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  NUXT_MAIL_SMTP: ${{ secrets.NUXT_MAIL_SMTP }}
  NUXT_MAIL_PORT: ${{ secrets.NUXT_MAIL_PORT }}
  NUXT_MAIL_USERNAME: ${{ secrets.NUXT_MAIL_USERNAME }}
  NUXT_MAIL_PASSWORD: ${{ secrets.NUXT_MAIL_PASSWORD }}
  NUXT_MAIL_TARGET: ${{ secrets.NUXT_MAIL_TARGET }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.4.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - run: npm run build --if-present
